### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by alexleft** [nullquant/ComfyUI-BrushNet#12]
After installing ComfyUI-BrushNet from ComfyUI-Manager,it prompt an "IMPORT FAILED" message.
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/16779585/32a43bf1-33e4-455f-97b7-9e8150bfcf95)

the console output:
```
Looking in indexes: https://mirrors.jlu.edu.cn/pypi/simple/
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Traceback (most recent call last):
  File "/data/prd/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/prd/ComfyUI/custom_nodes/ComfyUI-BrushNet/__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNetPipeline, BrushNetInpaint, BlendInpaint
  File "/data/prd/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 25, in <module>
    from .brushnet.pipeline_brushnet import StableDiffusionBrushNetPipeline
  File "/data/prd/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet/pipeline_brushnet.py", line 26, in <module>
    from diffusers.pipelines.pipeline_utils import DiffusionPipeline, StableDiffusionMixin
ImportError: cannot import name 'StableDiffusionMixin' from 'diffusers.pipelines.pipeline_utils' (/home/ai/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py)

Cannot import /data/prd/ComfyUI/custom_nodes/ComfyUI-BrushNet module for custom nodes: cannot import name 'StableDiffusionMixin' from 'diffusers.pipelines.pipeline_utils' (/home/ai/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py)

```
And when I install this node manually, the requirement  package "yaml" was missing in the pip source.
```
$ pip install -r requirements.txt 
Looking in indexes: https://mirrors.jlu.edu.cn/pypi/simple/
Requirement already satisfied: torch in /home/ai/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: diffusers in /home/ai/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.26.3)
Requirement already satisfied: accelerate in /home/ai/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.26.1)
Requirement already satisfied: numpy in /home/ai/miniconda3/envs/ComfyUI/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.26.4)
Requirement already satisfied: opencv-python in /home/ai/miniconda3/envs/ComfyUI/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (4.9.0.80)
Requirement already satisfied: Pillow in /home/ai/miniconda3/envs/ComfyUI/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (10.2.0)
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml
```
How to fix it?
I'm running miniconda and python==3.10.12,and the other nodes works normaly.

**Comment by nullquant** [comment]
Thanks for a detailed report. I just fixed imports, try it now.
