### ISSUE TITLE
About huggingface-hub version

### ISSUE THREAD

**Issue by hben35096** [nullquant/ComfyUI-BrushNet#122]
If I use: huggingface-hub 0.20.3
Will prompt:
`Cannot import /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-BrushNet module for custom nodes: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)`

Of course, after upgrading the huggingface-hub version, all the problems are solved. Can you write the huggingface-hub version requirements into the "requirements.txt" file?

**Comment by nullquant** [comment]
It is interesting, but the nodes do not use huggingface_hub library. I also didn't find uses of this library in ComfyUI. So, it seems your way of loading custom nodes needs it, do you use Manager?

**Comment by reaisheji** [comment]
This problem does exist, many people install it through the manager

**Comment by hben35096** [comment]
Here is the complete message:
```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-08 01:24:23.399507
** Platform: Linux
** Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
** Python executable: /root/miniconda3/bin/python
** ComfyUI Path: /root/autodl-tmp/ComfyUI
** Log path: /root/autodl-tmp/ComfyUI/comfyui.log

Prestartup times for custom nodes:
0.9 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 11012 MB, total RAM 384797 MB
pytorch version: 2.1.1+cu121
xformers version: 0.0.23
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using xformers cross attention
Total VRAM 11012 MB, total RAM 384797 MB
pytorch version: 2.1.1+cu121
xformers version: 0.0.23
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V5.16)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[ReActor] - STATUS - Running v0.5.0-b4 in ComfyUI
Torch version: 2.1.1+cu121
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz - Arch: x86_64 - OS: Linux 5.15.0-88-generic
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 2080 Ti
[Crystools INFO] NVIDIA Driver: 535.129.03
### Loading: ComfyUI-Manager (V2.46)
### ComfyUI Revision: 2341 [628f0b8e] | Released on '2024-07-07'
Traceback (most recent call last):
File "/root/autodl-tmp/ComfyUI/nodes.py", line 1907, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-BrushNet/__init__.py", line 1, in <module>
from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 8, in <module>
from accelerate import init_empty_weights, load_checkpoint_and_dispatch
File "/root/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
from .accelerator import Accelerator
File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

Cannot import /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-BrushNet module for custom nodes: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

Import times for custom nodes:
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/websocket_image_save.py
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/stability-ComfyUI-nodes
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_experiments
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-IC-Light
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Video-Matting
0.0 seconds (IMPORT FAILED): /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-BrushNet
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-AnimateDiff
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui-reactor-node
0.1 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Manager
0.5 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_InstantID
2.5 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Crystools
2.8 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

Starting server

```
I upgraded the manager to the latest version and tried to install a few plugins with it, and it worked smoothly until I installed "ComfyUI-BrushNet" or "kijai/ComfyUI-BrushNet-Wrapper" and I got the same error.

**Comment by hben35096** [comment]
I understand that the error is caused by the requirement "accelerate>=0.29.0". Is version 0.29.0 or higher really necessary?

**Comment by nullquant** [comment]
Ok, I found a culprit. `huggingface_hub>=0.21.0` should be added to `accelerate` library requirements. I added pull request for it.

**Comment by hben35096** [comment]
I think, limiting accelerate to less than 0.32.0 is an option, it has higher compatibility, and even if huggingface_hub is lower, say 0.20.3, it can still be compatible.

**Comment by nullquant** [comment]
The pull request of `accelerate` was approved and merged.

**Comment by nullquant** [comment]
> I think, limiting accelerate to less than 0.32.0 is an option, it has higher compatibility, and even if huggingface_hub is lower, say 0.20.3, it can still be compatible.

That is a good idea. Done it for a while.

**Comment by sataset** [comment]
i guess accelerate could be a bit relaxed now `>=0.29.0, !=0.32.0, 0.32.1,<=0.33.0` due to https://github.com/huggingface/accelerate/pull/2932

it also seems that they are constantly removing version bounds for tests and forgetting to add it back according to history in git blame
https://github.com/huggingface/accelerate/blame/main/setup.py
