### ISSUE TITLE
Failed to import the plug-in after downloading it

### ISSUE THREAD

**Issue by xiaoha000** [nullquant/ComfyUI-BrushNet#151]
E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-06 18:26:44.852231
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: E:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI_windows_portable\ComfyUI
** Log path: E:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.8 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65277 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
Adding E:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Loaded ControlNetPreprocessors nodes from E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.10.7)
[Impact Pack] Wildcards loading done.Loaded ImpactPack nodes from
 E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 15, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 8, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
Module 'diffusers' load failed. If you don't have it installed, do it:
pip install diffusers
[ComfyUI-Easy-Use] server: v1.2.4 Loaded
[ComfyUI-Easy-Use] web root: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
    from diffusers import ConsistencyDecoderVAE
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
Total VRAM 24564 MB, total RAM 65277 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V7.10.7)
[Impact Pack] Wildcards loading done.
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
### ComfyUI Revision: 2808 [69667290] *DETACHED | Released on '2024-11-04'
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.5.1+cu124
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[tinyterraNodes] Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Art is the most beautiful of all lies." - Claude Debussy

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.9 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.9 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by nullquant** [comment]
It is due to incompatibility between `diffusers`  and `huggingface_hub` versions. You should update your `diffusers` library. I also changed `requirements.txt`, so you can try to update the code and restart.
