### ISSUE TITLE
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):

### ISSUE THREAD

**Issue by xueqing0622** [nullquant/ComfyUI-BrushNet#160]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 15, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 20, in <module>
    from .unet_2d_blocks import (
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet\unet_2d_blocks.py", line 36, in <module>
    from diffusers.models.transformers.dual_transformer_2d import DualTransformer2DModel
  File "F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\transformers\__init__.py", line 13, in <module>
    from .prior_transformer import PriorTransformer
  File "F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\models\transformers\prior_transformer.py", line 9, in <module>
    from ...loaders import PeftAdapterMixin, UNet2DConditionLoadersMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (F:\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py)

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet module for custom nodes: Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (F:\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py)

**Comment by xueqing0622** [comment]
after update hunyuan video reequipment, error show.
accelerate >= 1.2.1
diffusers >= 0.31.0
transformers >= 4.47.0
jax >= 0.4.28
