### ISSUE TITLE
'NoneType' object has no attribute 'model'

### ISSUE THREAD

**Issue by buy3601223** [nullquant/ComfyUI-BrushNet#163]
前面运行还好好的，第三次运行出现错误了，很奇怪
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
BrushNet image.shape = torch.Size([1, 768, 543, 3]) mask.shape = torch.Size([1, 768, 543])
Potential memory leak detected with model BaseModel, doing a full garbage collect, for maximum performance avoid circular references in the model code.
WARNING, memory leak with model BaseModel. Please make sure it is not being referenced from somewhere.
Requested to load AutoencoderKL
Potential memory leak detected with model BaseModel, doing a full garbage collect, for maximum performance avoid circular references in the model code.
WARNING, memory leak with model BaseModel. Please make sure it is not being referenced from somewhere.
loaded completely 9.5367431640625e+25 319.11416244506836 True
BrushNet CL: image_latents shape = torch.Size([1, 4, 96, 67]) interpolated_mask shape = torch.Size([1, 1, 96, 67])
!!! Exception during processing !!! 'NoneType' object has no attribute 'model'
Traceback (most recent call last):
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 366, in model_update
    if type(loaded_model.model.model) in ModelsToUnload:
            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'

Prompt executed in 3.97 seconds

**Comment by hero8152** [comment]
我测试一下，单独跑brushnet或者单独跑PowerPaint 不会报错，一起跑brushnet跟PowerPaint 之后，再跑就报错

**Comment by buy3601223** [comment]
公司最初由4位国内首批电商网站建设卖家发掘市场需求，阖力创办，旨在解决互联网平台销售中遇到的运营难题。公司专注于互联网营销推广，主营业务涵盖店铺整体托管、网店装修、精准营销，视觉设计、客服外包、产品摄影、软件开发、培训咨询与微社群营销，网站建设推广，依托大数据优势，帮助企业快速建立全新的销售系统，助力企业转型提速，开启“互联网+”时代的新商业未来。
