### ISSUE TITLE
xl的inpaint模型加载报错

### ISSUE THREAD

**Issue by 807502278** [nullquant/ComfyUI-BrushNet#29]
got prompt
2024-04-29 15:13:51.896482 [rgthree] Using rgthree's optimized recursive execution.
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
!!! Exception during processing!!! Trying to set a tensor of shape torch.Size([320]) in "bias" (which has shape torch.Size([640])), this look incorrect.
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI-aki-v1_new\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI-aki-v1_new\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 64, in brushnet_loading
    brushnet_model = load_checkpoint_and_dispatch(
  File "D:\AI\ComfyUI-aki-v1_new\python\lib\site-packages\accelerate\big_modeling.py", line 607, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "D:\AI\ComfyUI-aki-v1_new\python\lib\site-packages\accelerate\utils\modeling.py", line 1734, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "D:\AI\ComfyUI-aki-v1_new\python\lib\site-packages\accelerate\utils\modeling.py", line 358, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([320]) in "bias" (which has shape torch.Size([640])), this look incorrect.

2024-04-29 15:13:52.779639 #45 [BrushNetLoader]: 0.88s

**Comment by nullquant** [comment]
SDXL BrushNet is not implemented yet.
