### ISSUE TITLE
!!! Exception during processing!!! 'model.diffusion_model.input_blocks.0.0.weight'

### ISSUE THREAD

**Issue by DreamLoveBetty** [nullquant/ComfyUI-BrushNet#59]
load checkpoint Error reporting:

!!! Exception during processing!!! 'model.diffusion_model.input_blocks.0.0.weight'
Traceback (most recent call last):
  File "D:\Program\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Program\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Program\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Program\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 124, in load_checkpoint
    return super().load_checkpoint(**kwargs)
  File "D:\Program\ComfyUI\nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "D:\Program\ComfyUI\comfy\sd.py", line 517, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.")
  File "D:\Program\ComfyUI\comfy\model_detection.py", line 194, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix)
  File "D:\Program\ComfyUI\comfy\model_detection.py", line 78, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'

**Comment by nullquant** [comment]
Could you post complete log with BrushNet nodes messages?

**Comment by DreamLoveBetty** [comment]
The checkpoint was downloaded from Google Cloud, and all six checkpoints are in the same situation. The workflow execution has not yet reached the Brushnet module, so I have to take a screenshot. I hope it is helpful. Please take a look.

![error](https://github.com/nullquant/ComfyUI-BrushNet/assets/138059406/f224ff84-3159-450f-b39c-01fd2f1723cc)

**Comment by nullquant** [comment]
Oh, did you take base model from BrushNet's google drive? I think it is the problem. You should take full version not just unet from  CivitAI: https://civitai.com/models/4201/realistic-vision-v60-b1 Or you could just take any base model you want.

**Comment by DreamLoveBetty** [comment]
Well, there's no problem using other models. Thank you for your answer. You can close this issue now.
