### ISSUE TITLE
BrushNetLoader Not Installing

### ISSUE THREAD

**Issue by UbuntuJohn** [nullquant/ComfyUI-BrushNet#87]
I've been trying to get this to work all day. Installed it through ComfyUI-Manager. I tried to git pull any update but it says it's already up to date. I don't receive any sort of errors that it didn't work. What am I missing?

![Screenshot 2024-05-13 051509](https://github.com/nullquant/ComfyUI-BrushNet/assets/4097798/951d6d6b-58f4-467f-83c6-70cf0ee93c96)

**Comment by nullquant** [comment]
When ComfyUI starts it prints a log. Every custom nodes errors are there. Please, post it and I will try to help you. 

Also ComfyUI Manager sometimes just fails to install custom nodes.

**Comment by ogladkov** [comment]
Same problem here

**Comment by nullquant** [comment]
I can't help you without any information about your installation of ComfyUI. OS, ComfyUI version, other custom nodes, etc... It is all in the log.

**Comment by UbuntuJohn** [comment]
`

J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-13 11:03:03.671454
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.6 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32693 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\colour\utilities\verbose.py:265: ColourUsageWarning: "Matplotlib" related API features are not available: "No module named 'matplotlib'".
See the installation guide for more information: https://www.colour-science.org/installation-guide/
  warn(*args, **kwargs)  # noqa: B028
Adding J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
Could not find ControlNetPreprocessors nodes
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Could not find IPAdapter nodes
Loaded VideoHelperSuite from J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
Could not load ImpactPack nodes Could not find ImpactPack nodes
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, PowerPaintCLIPLoader, PowerPaint, CutForInpaint
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 16, in <module>
    from accelerate import init_empty_weights, load_checkpoint_and_dispatch
ModuleNotFoundError: No module named 'accelerate'

Cannot import J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet module for custom nodes: No module named 'accelerate'
### Loading: ComfyUI-Manager (V2.32.3)
### ComfyUI Revision: 2178 [ece5acb8] | Released on '2024-05-12'
------------------------------------------
### N-Suite Revision: dbeb9ae9
Current version of packaging: 24.0
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.9.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Current version of skbuild: 0.17.6
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu121
Current version of timm: 0.9.12
[ReActor] - STATUS - Running v0.5.0-b2 in ComfyUI
Torch version: 2.3.0+cu121
No module named 'ultralytics'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
2024-05-13 11:03:14.391055: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-13 11:03:15.839086: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM_Nodes.py", line 6, in <module>
    from .LCM.lcm_pipeline_inpaint import LatentConsistencyModelPipeline_inpaint, LCMScheduler_X
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy\LCM\lcm_pipeline_inpaint.py", line 26, in <module>
    from diffusers import AutoencoderKL, ConfigMixin, DiffusionPipeline, SchedulerMixin, UNet2DConditionModel, logging, AsymmetricAutoencoderKL
ModuleNotFoundError: No module named 'diffusers'

Cannot import J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy module for custom nodes: No module named 'diffusers'
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "The best revenge is massive success." - Frank Sinatra


Import times for custom nodes:
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyI2I
   0.0 seconds (IMPORT FAILED): J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-video-batches
   0.0 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\komojini-comfyui-nodes
   0.1 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.4 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui
   0.7 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   1.4 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   2.5 seconds: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.9 seconds (IMPORT FAILED): J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
`

**Comment by Troyificus** [comment]
Same problem here. Running Windows 10, updated ComfyUI to latest version today, Windows stand-alone install.

`[ERROR] An error occurred while retrieving information for the 'BrushNetLoader' node.
Traceback (most recent call last):
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 52, in INPUT_TYPES
    files, inpaint_path = get_files_with_extension('inpaint')
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 586, in get_files_with_extension
    inpaint_path = os.path.join(folder_paths.base_dir, inpaint_path)
AttributeError: module 'folder_paths' has no attribute 'base_dir'

[ERROR] An error occurred while retrieving information for the 'PowerPaintCLIPLoader' node.
Traceback (most recent call last):
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 139, in INPUT_TYPES
    inpaint_files, inpaint_path = get_files_with_extension('inpaint', ['bin'])
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 586, in get_files_with_extension
    inpaint_path = os.path.join(folder_paths.base_dir, inpaint_path)
AttributeError: module 'folder_paths' has no attribute 'base_dir'

[ERROR] An error occurred while retrieving information for the 'brushnet_ipadapter_matteo' node.
Traceback (most recent call last):
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\nodes.py", line 596, in INPUT_TYPES
    "ipadapter": (folder_paths.get_filename_list("ipadapter"), ),
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 225, in get_filename_list
    out = get_filename_list_(folder_name)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 192, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'ipadapter'`

**Comment by UbuntuJohn** [comment]
I just re-installed it again and noticed I'm also experiencing the same/similar issue as @Troyificus 

`To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
[ERROR] An error occurred while retrieving information for the 'BrushNetLoader' node.
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 52, in INPUT_TYPES
    files, inpaint_path = get_files_with_extension('inpaint')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 586, in get_files_with_extension
    inpaint_path = os.path.join(folder_paths.base_dir, inpaint_path)
                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'folder_paths' has no attribute 'base_dir'

[ERROR] An error occurred while retrieving information for the 'PowerPaintCLIPLoader' node.
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 139, in INPUT_TYPES
    inpaint_files, inpaint_path = get_files_with_extension('inpaint', ['bin'])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 586, in get_files_with_extension
    inpaint_path = os.path.join(folder_paths.base_dir, inpaint_path)
                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'folder_paths' has no attribute 'base_dir'

`

**Comment by nullquant** [comment]
Sorry guys, my bad. Last commit had a bug, please update again.

**Comment by UbuntuJohn** [comment]
For me at least, it didn't fix the issue.

`To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
[ERROR] An error occurred while retrieving information for the 'BrushNetLoader' node.
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 52, in INPUT_TYPES
    files, inpaint_path = get_files_with_extension('inpaint')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 588, in get_files_with_extension
    raise Exception("Can't find", folder_name, " path")
Exception: ("Can't find", 'inpaint', ' path')

[ERROR] An error occurred while retrieving information for the 'PowerPaintCLIPLoader' node.
Traceback (most recent call last):
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 139, in INPUT_TYPES
    inpaint_files, inpaint_path = get_files_with_extension('inpaint', ['bin'])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 588, in get_files_with_extension
    raise Exception("Can't find", folder_name, " path")
Exception: ("Can't find", 'inpaint', ' path')
`

**Comment by UbuntuJohn** [comment]
> Is it because there's a space before the word "path" ?

Removing the space in code didn't help, so I guess not. I'm not much of a Python developer other than building basic CRUD apps using TKinter.

**Comment by HackerTox** [comment]
just Remove red area：
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/163481608/bbe6386e-22bc-493f-b646-cd32085e19a5)

**Comment by Troyificus** [comment]
That fixed it for me! Grabbed the new update and created a 'inpaint' folder in my models folder.

**Comment by ogladkov** [comment]
Now its ok! Thanks for amazing work guys!

**Comment by nullquant** [comment]
I removed the exception, didn't think it will be raised at install time, sorry.
